name: initial

on: 
  workflow_dispatch:
    inputs:
      env:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: echo file
        run: echo ${{ github.event.inputs.env}}
